made tests a bit more data driven

diff --git a/test/run_test b/test/run_test
--- a/test/run_test
+++ b/test/run_test
@@ -1,34 +1,30 @@
 #!/bin/bash
-rm output/acme_registrations*.png output/acme_revenue*.png 2> /dev/null
-error_file=/tmp/plot_time_series_error.txt
-rm ${error_file} 2> /dev/null
 
-echo "generating registrations graph"
-../plot_time_series --width=1200 --height=700 --x_spacing=week --csv_filename=test_data/acme_registrations.csv \
-  --output_filename=output/acme_registrations.png --show_gridlines --title="Acme Registrations: %s to %s" \
-  --y_title="Number Registrations" --remove_outliers 2>> ${error_file}
+rm output/*.png 2> /dev/null
 
-echo "generating registrations thumb"
-../plot_time_series --width=500 --height=400 --x_spacing=month --csv_filename=test_data/acme_registrations.csv \
-  --output_filename=output/acme_registrations_thumb.png --point_color=gray80 --sunday_point_color=gray80 \
-  --remove_outliers --smoothness=0.8 2>> ${error_file}
+while read test_def; do
+  name=`echo $test_def | cut -f1 -d,`
+  test=`echo $test_def | cut -f2 -d,`
+  global_result=0
 
-echo "generating revenue graph"
-../plot_time_series --width=1200 --height=700 --x_spacing=week --csv_filename=test_data/acme_revenue.csv \
-  --output_filename=output/acme_revenue.png --show_gridlines --title="Acme Revenue: %s to %s" \
-  --remove_outliers 2>> ${error_file}
+  echo -n "running test ${name} ... "
+  eval ${test}
+  if test $? -ne 0
+  then
+    echo "FAILED"
+    global_result=1
+  else
+    echo "passed"
+  fi
+ 
+done < tests.txt
 
-echo "generating revenue thumb"
-../plot_time_series --width=500 --height=400 --x_spacing="2 months" --csv_filename=test_data/acme_revenue.csv \
-  --output_filename=output/acme_revenue_thumb.png --point_color=gray80 --sunday_point_color=gray80 \
-  --remove_outliers --smoothness=0.8 2>> ${error_file}
+echo
+if test ${global_result} -eq 0
+then
+  echo "All tests passed"
+else
+  echo "Some tests FAILED"
+fi
 
-echo "generating revenue graph with targets"
-../plot_time_series --width=1200 --height=700 --x_spacing=week --csv_filename=test_data/acme_revenue.csv \
-  --output_filename=output/acme_revenue_targets.png --show_gridlines --title="Acme Revenue: %s to %s" --remove_outliers \
-  --special_points_filename=test_data/acme_revenue_targets.csv --special_points_color=cornflowerblue --point_color=gray80 \
-  --sunday_point_color=gray80 2>> ${error_file}
-
-cat ${error_file}
-
-open output/acme_revenue*.png output/acme_registrations*.png
+open output/*.png
